# Form implementation generated from reading ui file 'C:\Users\crabt\OneDrive\Рабочий стол\Новая папка (2)\ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ListItem import MusicList as Music
import random
from pygame import mixer


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(219, 320, 421, 86))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(85, 255, 0)\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color:rgb(111, 111, 111)\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 0, 0)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_8.setStyleSheet("}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-color:rgb(111, 111, 111)\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(540, 20, 76, 24))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 0, 0)\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(275, 0, 251, 321))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 20, 76, 24))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color:rgb(255, 0, 0)\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        def on():
            self.listWidget.addItems(Music)

        def off():
            self.listWidget.clear()

        def rand():
            random.shuffle(Music)

        def play():
            mixer.init()
            if Music[0] == "Rare - NEFFEX":
                mixer.music.load("NEFFEX - Rare.mp3")
                mixer.music.play()

            elif Music[0] == "Hero - Skillet":
                mixer.music.load("Skillet - Hero.mp3")
                mixer.music.play()

            elif Music[0] == "Gladiator - Jann":
                mixer.music.load("Jann - Gladiator.mp3")
                mixer.music.play()

            elif Music[0] == "Fight Back - NEFFEX":
                mixer.music.load("NEFFEX - Fight Back.mp3")
                mixer.music.play()

            elif Music[0] == "Feel Invincible - Skillet":
                mixer.music.load("Skillet - Feel Invincible.mp3")
                mixer.music.play()

        def stop():
            mixer.init()
            mixer.music.stop()

        def pause():
            mixer.init()
            mixer.music.pause()

        def unpause():
            mixer.init()
            mixer.music.unpause()

        def next():
            mixer.init()
            rand()
            if Music[1] == "Rare - NEFFEX":
                mixer.music.load("NEFFEX - Rare.mp3")
                mixer.music.play()

            elif Music[1] == "Hero - Skillet":
                mixer.music.load("Skillet - Hero.mp3")
                mixer.music.play()

            elif Music[1] == "Gladiator - Jann":
                mixer.music.load("Jann - Gladiator.mp3")
                mixer.music.play()

            elif Music[1] == "Fight Back - NEFFEX":
                mixer.music.load("NEFFEX - Fight Back.mp3")
                mixer.music.play()

            elif Music[1] == "Feel Invincible - Skillet":
                mixer.music.load("Skillet - Feel Invincible.mp3")
                mixer.music.play()

        self.pushButton.clicked.connect(rand)
        self.pushButton_2.clicked.connect(play)
        self.pushButton_3.clicked.connect(stop)
        self.pushButton_4.clicked.connect(on)
        self.pushButton_5.clicked.connect(off)
        self.pushButton_6.clicked.connect(pause)
        self.pushButton_7.clicked.connect(unpause)
        self.pushButton_8.clicked.connect(next)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Rand"))
        self.pushButton_2.setText(_translate("MainWindow", "Play"))
        self.pushButton_6.setText(_translate("MainWindow", "Pause"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.pushButton_8.setText(_translate("MainWindow", "Next"))
        self.pushButton_7.setText(_translate("MainWindow", "UnPause"))
        self.pushButton_4.setText(_translate("MainWindow", "On"))
        self.pushButton_5.setText(_translate("MainWindow", "Off"))

